### ISSUE TITLE
Teste de consulta da API do Twitter por usuário e filtrando por informações da Proposição, como Número e Apelido.

### ISSUE THREAD

**Issue by ArthurJahn** [parlametria/leggo-twitter-dados#41]

**Comment by andersonms1** [comment]
@ArthurJahn devo inserir esse código do estudo em qual repo? Ou criar um separado só para esse fim?

**Comment by andersonms1** [comment]
@ArthurJahn 
Não consigo buildar o ambiente do `airflow`.

1. Clonei o [repo](https://github.com/parlametria/airflow)
2. Preenchi as variaveis de ambiente

E ao tentar dar o build o erro acontece

``` make dev-build ```

```shell
docker-compose build
Sending build context to Docker daemon  114.3kB
Step 1/7 : FROM python:3.8.10-slim-buster
 ---> add28abdb01c
Step 2/7 : WORKDIR /airflow
 ---> Using cache
 ---> 232557bea9db
Step 3/7 : RUN pip install --upgrade pip
 ---> Using cache
 ---> e14b871eefd8
Step 4/7 : COPY requirements.txt /airflow/
 ---> Using cache
 ---> b1fc4a6271c7
Step 5/7 : COPY . /airflow/
 ---> Using cache
 ---> 5131cdc34475
Step 6/7 : RUN pip install -r requirements.txt
 ---> Running in f14bf3f57493
Collecting apache-airflow==2.1.2
  Downloading apache_airflow-2.1.2-py3-none-any.whl (5.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 4.9 MB/s eta 0:00:00
Collecting apache-airflow-providers-docker==2.1.0
  Downloading apache_airflow_providers_docker-2.1.0-py3-none-any.whl (26 kB)
Collecting python-dotenv==0.19.0
  Downloading python_dotenv-0.19.0-py2.py3-none-any.whl (17 kB)
Collecting python-dateutil==2.8.2
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 2.1 MB/s eta 0:00:00
Collecting psycopg2==2.9.3
  Downloading psycopg2-2.9.3.tar.gz (380 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.6/380.6 KB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-pzt7jm6w/psycopg2.egg-info
      writing /tmp/pip-pip-egg-info-pzt7jm6w/psycopg2.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-pzt7jm6w/psycopg2.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-pip-egg-info-pzt7jm6w/psycopg2.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-pzt7jm6w/psycopg2.egg-info/SOURCES.txt'
      
      Error: pg_config executable not found.
      
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
      
          python setup.py build_ext --pg-config /path/to/pg_config build ...
      
      or with the pg_config option in 'setup.cfg'.
      
      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.
      
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Sending build context to Docker daemon  114.3kB
Step 1/7 : FROM python:3.8.10-slim-buster
 ---> add28abdb01c
Step 2/7 : WORKDIR /airflow
 ---> Using cache
 ---> 232557bea9db
Step 3/7 : RUN pip install --upgrade pip
 ---> Using cache
 ---> e14b871eefd8
Step 4/7 : COPY requirements.txt /airflow/
 ---> Using cache
 ---> b1fc4a6271c7
Step 5/7 : COPY . /airflow/
 ---> Using cache
 ---> 5131cdc34475
Step 6/7 : RUN pip install -r requirements.txt
 ---> Running in b154e76fad2a
Collecting apache-airflow==2.1.2
  Downloading apache_airflow-2.1.2-py3-none-any.whl (5.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 7.8 MB/s eta 0:00:00
Collecting apache-airflow-providers-docker==2.1.0
  Downloading apache_airflow_providers_docker-2.1.0-py3-none-any.whl (26 kB)
Collecting python-dotenv==0.19.0
  Downloading python_dotenv-0.19.0-py2.py3-none-any.whl (17 kB)
Collecting python-dateutil==2.8.2
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 22.5 MB/s eta 0:00:00
Collecting psycopg2==2.9.3
  Downloading psycopg2-2.9.3.tar.gz (380 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.6/380.6 KB 2.8 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-47sdp23a/psycopg2.egg-info
      writing /tmp/pip-pip-egg-info-47sdp23a/psycopg2.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-47sdp23a/psycopg2.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-pip-egg-info-47sdp23a/psycopg2.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-47sdp23a/psycopg2.egg-info/SOURCES.txt'
      
      Error: pg_config executable not found.
      
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
      
          python setup.py build_ext --pg-config /path/to/pg_config build ...
      
      or with the pg_config option in 'setup.cfg'.
      
      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.
      
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
2 errors occurred:
	* Status: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1, Code: 1
	* Status: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1, Code: 1


make: *** [Makefile:5: dev-build] Erro 1


```

**Comment by fabio1079** [comment]
> @ArthurJahn Não consigo buildar o ambiente do `airflow`.
> 
>     1. Clonei o [repo](https://github.com/parlametria/airflow)
> 
>     2. Preenchi as variaveis de ambiente
> 
> 
> E ao tentar dar o build o erro acontece
> 
> `make dev-build`
> 
> ```shell
> docker-compose build
> Sending build context to Docker daemon  114.3kB
> Step 1/7 : FROM python:3.8.10-slim-buster
>  ---> add28abdb01c
> Step 2/7 : WORKDIR /airflow
>  ---> Using cache
>  ---> 232557bea9db
> Step 3/7 : RUN pip install --upgrade pip
>  ---> Using cache
>  ---> e14b871eefd8
> Step 4/7 : COPY requirements.txt /airflow/
>  ---> Using cache
>  ---> b1fc4a6271c7
> Step 5/7 : COPY . /airflow/
>  ---> Using cache
>  ---> 5131cdc34475
> Step 6/7 : RUN pip install -r requirements.txt
>  ---> Running in f14bf3f57493
> Collecting apache-airflow==2.1.2
>   Downloading apache_airflow-2.1.2-py3-none-any.whl (5.2 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 4.9 MB/s eta 0:00:00
> Collecting apache-airflow-providers-docker==2.1.0
>   Downloading apache_airflow_providers_docker-2.1.0-py3-none-any.whl (26 kB)
> Collecting python-dotenv==0.19.0
>   Downloading python_dotenv-0.19.0-py2.py3-none-any.whl (17 kB)
> Collecting python-dateutil==2.8.2
>   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 2.1 MB/s eta 0:00:00
> Collecting psycopg2==2.9.3
>   Downloading psycopg2-2.9.3.tar.gz (380 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.6/380.6 KB 3.2 MB/s eta 0:00:00
>   Preparing metadata (setup.py): started
>   Preparing metadata (setup.py): finished with status 'error'
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [23 lines of output]
>       running egg_info
>       creating /tmp/pip-pip-egg-info-pzt7jm6w/psycopg2.egg-info
>       writing /tmp/pip-pip-egg-info-pzt7jm6w/psycopg2.egg-info/PKG-INFO
>       writing dependency_links to /tmp/pip-pip-egg-info-pzt7jm6w/psycopg2.egg-info/dependency_links.txt
>       writing top-level names to /tmp/pip-pip-egg-info-pzt7jm6w/psycopg2.egg-info/top_level.txt
>       writing manifest file '/tmp/pip-pip-egg-info-pzt7jm6w/psycopg2.egg-info/SOURCES.txt'
>       
>       Error: pg_config executable not found.
>       
>       pg_config is required to build psycopg2 from source.  Please add the directory
>       containing pg_config to the $PATH or specify the full executable path with the
>       option:
>       
>           python setup.py build_ext --pg-config /path/to/pg_config build ...
>       
>       or with the pg_config option in 'setup.cfg'.
>       
>       If you prefer to avoid building psycopg2 from source, please install the PyPI
>       'psycopg2-binary' package instead.
>       
>       For further information please check the 'doc/src/install.rst' file (also at
>       <https://www.psycopg.org/docs/install.html>).
>       
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> Sending build context to Docker daemon  114.3kB
> Step 1/7 : FROM python:3.8.10-slim-buster
>  ---> add28abdb01c
> Step 2/7 : WORKDIR /airflow
>  ---> Using cache
>  ---> 232557bea9db
> Step 3/7 : RUN pip install --upgrade pip
>  ---> Using cache
>  ---> e14b871eefd8
> Step 4/7 : COPY requirements.txt /airflow/
>  ---> Using cache
>  ---> b1fc4a6271c7
> Step 5/7 : COPY . /airflow/
>  ---> Using cache
>  ---> 5131cdc34475
> Step 6/7 : RUN pip install -r requirements.txt
>  ---> Running in b154e76fad2a
> Collecting apache-airflow==2.1.2
>   Downloading apache_airflow-2.1.2-py3-none-any.whl (5.2 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 7.8 MB/s eta 0:00:00
> Collecting apache-airflow-providers-docker==2.1.0
>   Downloading apache_airflow_providers_docker-2.1.0-py3-none-any.whl (26 kB)
> Collecting python-dotenv==0.19.0
>   Downloading python_dotenv-0.19.0-py2.py3-none-any.whl (17 kB)
> Collecting python-dateutil==2.8.2
>   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 22.5 MB/s eta 0:00:00
> Collecting psycopg2==2.9.3
>   Downloading psycopg2-2.9.3.tar.gz (380 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.6/380.6 KB 2.8 MB/s eta 0:00:00
>   Preparing metadata (setup.py): started
>   Preparing metadata (setup.py): finished with status 'error'
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [23 lines of output]
>       running egg_info
>       creating /tmp/pip-pip-egg-info-47sdp23a/psycopg2.egg-info
>       writing /tmp/pip-pip-egg-info-47sdp23a/psycopg2.egg-info/PKG-INFO
>       writing dependency_links to /tmp/pip-pip-egg-info-47sdp23a/psycopg2.egg-info/dependency_links.txt
>       writing top-level names to /tmp/pip-pip-egg-info-47sdp23a/psycopg2.egg-info/top_level.txt
>       writing manifest file '/tmp/pip-pip-egg-info-47sdp23a/psycopg2.egg-info/SOURCES.txt'
>       
>       Error: pg_config executable not found.
>       
>       pg_config is required to build psycopg2 from source.  Please add the directory
>       containing pg_config to the $PATH or specify the full executable path with the
>       option:
>       
>           python setup.py build_ext --pg-config /path/to/pg_config build ...
>       
>       or with the pg_config option in 'setup.cfg'.
>       
>       If you prefer to avoid building psycopg2 from source, please install the PyPI
>       'psycopg2-binary' package instead.
>       
>       For further information please check the 'doc/src/install.rst' file (also at
>       <https://www.psycopg.org/docs/install.html>).
>       
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> 2 errors occurred:
> 	* Status: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1, Code: 1
> 	* Status: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1, Code: 1
> 
> 
> make: *** [Makefile:5: dev-build] Erro 1
> ```

Esse erro foi descuido de minha parte ao implementar o ambiente de produção do airflow. Nesse caso foi adicionada a lib psycopg2 ao requerements.txt mas como em dev não se usa o postgresql então o Dockerfile.dev não tem o pacote libpq-dev que é instalado no Dockerfile.prod. Essa é a origem do erro.

Subi um fix commit na main que corrige esse problema. 
https://github.com/parlametria/airflow/commit/691f2e38ddb4619f19073d93aa782fb29bff7e29

**Comment by ArthurJahn** [comment]
@andersonms1 acredito que esse trabalho está concluído! Agora vamos seguir na direção da issue [leggo-painel#463](https://github.com/parlametria/leggo-painel/issues/463)
